### ISSUE TITLE
feature: add api support for hosting a reward model

### ISSUE THREAD

**Issue by ftmtk** [OpenRLHF/OpenRLHF#151]
I want to use a 70b parameter model as my reward model. It is inefficient to load such model from pretrained and ideally should be queried through an api. However, the existing class does not support such usage.

Could this feature be implemented?

Or if it has, could someone point me to its usage as I cannot find it.

Kind thanks

**Comment by wwxFromTju** [comment]
@hijkzzz I can make the ref and reward models into api services, and I can develop them if needed

**Comment by ftmtk** [comment]
@hijkzzz Thanks for point that out.

I think the same issue goes for the policy at rollout stage where if I want to train a 33B or even larger policy model w/ Adam, I won't be able to fit the model on a single gpu w/ 80GB mem. It's much harder to orchestrate parallel compute at rollout stage but I think it's possible.

A solution at the cost of caching compute would be like
At train stage:
gpu0,1,2,3 reserved for training policy

At rollout stage:
gpu0,1,2,3 partitioned to host max number of process for the policy (say 2; process_id=0,1)
gpu10,11,12,13 remotely at api port {1234, 1235} host max number of process for the policy (say2; process_id=10,11)

gpu20,21,22,23 host a very large reward model

Then the num_processes for batch_inference can be increased to 4, thus speed up the rollout process by a factor of 4.
gpu0,1,2,3 would be the expensive machines like H100; gpu10,11,12,13,20,21,22,23 would be some cost-effective inference machines (not necessary NV machines).

**Comment by catqaq** [comment]
> @hijkzzz我可以将ref和reward模型做成api服务，如果需要我可以开发它们

Maybe we can support function like request_remote_rm?

**Comment by wwxFromTju** [comment]
@catqaq Yes we can make an http service
