### ISSUE TITLE
The tokenizer of reward model and policy model.

### ISSUE THREAD

**Issue by eyuansu62** [OpenRLHF/OpenRLHF#242]
From the code, the tokenizer of reward model seems to be same as policy model？

**Comment by hijkzzz** [comment]
Yes

**Comment by eyuansu62** [comment]
Is there a situation where the tokenizer are different?

**Comment by zkshan2002** [comment]
Same request. Is it possible to support reward tokenizer different from actor tokenizer?

**Comment by hijkzzz** [comment]
please use the remote reward model.
