### ISSUE TITLE
Support ORPO

### ISSUE THREAD

**Issue by paulcx** [OpenRLHF/OpenRLHF#253]
Is it considered a new feature ORPO？

ORPO, a technique that replaces SFT+DPO/PPO was released recently. I saw @_philschmid's post regarding it yesterday. Gave ORPO a shot with phi-2 and @argilla_io dpo-mix-7k. 
Model: https://huggingface.co/abideen/phi2-pro. LazyORPO (Automated): https://colab.research.google.com/drive/19ci5XIcJDxDVPY2xC1ftZ5z1kc2ah_rx?usp=sharing

official repository: https://github.com/xfactlab/orpo

**Comment by hijkzzz** [comment]
Welcome everyone to contribute ORPO~
Our engineers have limited bandwidth at the moment~
