### ISSUE TITLE
How long does single LLM's tunning reuqired?

### ISSUE THREAD

**Issue by alphahumancoder** [OpenRLHF/OpenRLHF#262]

**Comment by alphahumancoder** [comment]
I mean 7B and 13B models

**Comment by hijkzzz** [comment]
> It depends on your datasets and GPUs, we have some benchmark for reference: https://github.com/OpenLLMAI/OpenRLHF/tree/wuxibin/benchmark/benchmark

This performance data in this branch is not optimized and we will further adjust the configs in the official technical report
