### ISSUE TITLE
Issue with models not using `position_ids`

### ISSUE THREAD

**Issue by kfertakis** [OpenRLHF/OpenRLHF#270]
I think this issue relates to #217 and #218. Some models, for example `facebook/opt-1.3b`,  don't accept `position_ids` as an argument and current implementation using it (used [here](https://github.com/OpenLLMAI/OpenRLHF/blob/9f1707201d8a8f40ece44abd6008c9ba56d02cb8/openrlhf/models/actor.py#L176), [here](https://github.com/OpenLLMAI/OpenRLHF/blob/9f1707201d8a8f40ece44abd6008c9ba56d02cb8/openrlhf/models/model.py#L201) and [here](https://github.com/OpenLLMAI/OpenRLHF/blob/9f1707201d8a8f40ece44abd6008c9ba56d02cb8/openrlhf/models/model.py#L262)) leads to the following error. Is there a way this argument is conditional to whether the model used supports it as input?

`TypeError: OPTModel.forward() got an unexpected keyword argument 'position_ids'`

Thank you,

**Comment by hijkzzz** [comment]
Interesting issue. Let me figure out how to fix it.

**Comment by hijkzzz** [comment]
fixed by hf
