### ISSUE TITLE
Custom ExperienceMaker

### ISSUE THREAD

**Issue by mgerstgrasser** [OpenRLHF/OpenRLHF#285]
I have a use case where I'd like to use a custom `ExperienceMaker` class instead of either of the provided ones. As far as I can tell, there isn't currently a way to configure the experience maker class used by `PPOTrainer` / `ActorPPOTrainer`.

Would you be open to a PR that makes this configurable? 

And if yes, would the best way of doing this be to put it into the `DeepspeedStrategy`?

**Comment by hijkzzz** [comment]
I think `ExperienceMaker ` has nothing to do with DeepSpeed
 I would like to know what kind of `ExperienceMaker ` maker you need first

**Comment by hijkzzz** [comment]
> The alternative would be to e.g. pass the experience maker class as an optional argument the the Trainer constructor, but in the Ray case that would require passing it through several other objects as well, i.e. more changes.

I think it's probably better this way

Welcome to have related MR contributions~

**Comment by mgerstgrasser** [comment]
OK! I'll test this on my side for a bit to make sure it covers all the use cases I have in mind. I'll open a PR in a couple of weeks.
