### ISSUE TITLE
[Question] EOS in reward model dataset

### ISSUE THREAD

**Issue by qwenzo** [OpenRLHF/OpenRLHF#300]
Hi, 

first of all thank you very much for the repo!
I would like to ask, is the EOS token in the reward model dataset necessary for the model? I'm using a gpt2 model where EOS is used for BOS and EOS is not usually used. That's why I was wondering if maybe this token is needed for reward modeling or is it model specific?

https://github.com/OpenLLMAI/OpenRLHF/blob/072e286a5c5f3cd6acf2c9ad7e4ef727a8dedb83/openrlhf/datasets/reward_dataset.py#L148

Thank you!

**Comment by hijkzzz** [comment]
Usually, we use an EOS token to output the reward value.
So we did not consider the situation of GPT-2

**Comment by qwenzo** [comment]
Hi, thank you for the reply. What is a possible way to fix this? Should I use a new special token?

**Comment by KunBB** [comment]
> Hi, thank you for the reply. What is a possible way to fix this? Should I use a new special token?

You can try to allocate an unused special token instead.

**Comment by pagepal666** [comment]
Usually, we use an EOS token to output the reward value. So we did not consider the situation of GPT-2

1. Why use this EOS? Can we not add EOS? Can we directly input the sentence into RM to output a scalar value? EOS is also not added to the training set when training RM.
2. If adding EOS, the final token needs to be replaced with EOS when using it.
