### ISSUE TITLE
Suggestion on the configurations

### ISSUE THREAD

**Issue by Ricardokevins** [OpenRLHF/OpenRLHF#304]
Hello, great job and very neat code and design!

I would like to inquire if there are more detailed recommendations for the design of rollout batch, train batch, and the number of nodes for each component (actor, etc.). Particularly, a brief introduction to the meanings of these hyperparameters and the impact of these settings on performance and computational efficiency.

**Comment by hijkzzz** [comment]
Thank you for your suggestions.
rollout_batch_size is the PPO experience_replay_buffer size
number of nodes  is the machine nodes for each model
train_batch is the train batch size
micro train batch is the batch size per GPU(larger better)
