### ISSUE TITLE
DPO Finetuning constantly gives preference loss as 0.6931

### ISSUE THREAD

**Issue by mandyyyyii** [OpenRLHF/OpenRLHF#364]
I checked the model gradient and find it retuned 'None'. Anyone have similar issue?

**Comment by hijkzzz** [comment]
Did this occur on the default dataset we provided?

**Comment by mandyyyyii** [comment]
No, I use customized dataset

**Comment by hijkzzz** [comment]
> No, I use customized dataset

Please refer to the 
https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/datasets/reward_dataset.py
to organize the datasets.

**Comment by mandyyyyii** [comment]
Yes. I use similar template for the customized dataset and it works fine for SFT method.

**Comment by hijkzzz** [comment]
It works well on my side
```
Train step of epoch 0:   2%|_                               | 189/12500 [02:46<2:41:06,  1.27it/s, preference_loss=0.769, chosen_reward=-0.14, reject_reward=-0.0509, acc_mean=0.583, loss_mean=0.669]
```

**Comment by wzq016** [comment]
May not be relevant. 

0.6931 is ln2, which means r(win) = r(lose) almost everywhere. 

One probable reason is that the customized dataset is too hard, for example, y_w and y_l is too close and only differ a few tokens, or there are bugs in the dataset preparation, for example, y_w = y_l .

**Comment by mandyyyyii** [comment]
Hi, after I set the lr=1e-7, I can see some loss change. However, the dpo loss drops sharply and approach near 0. For this case, would it be possible that the positive and negative samples in the dataset are excessively dissimilar to each other?

**Comment by wzq016** [comment]
There are a lot of possible reasons, such as bugs in processing.  If there is a space token at the beginning of every y_l, and no space token at the beginning of every y_w. Then model may quickly converge without learning meaning signals.

**Comment by mandyyyyii** [comment]
Hi, thank you so much. It is due to the preprocessing where rejected sample is not masked properly.
