### ISSUE TITLE
Difference between `DeepSpeedEngine.save_checkpoint()` and `DeepSpeedStrategy.save_model()`

### ISSUE THREAD

**Issue by ZhaofengWu** [OpenRLHF/OpenRLHF#365]
What's the difference between these two methods? Is it mostly that (1) `DeepSpeedStrategy.save_model()` saves the model in a format that is HF-compatible; (2) `DeepSpeedEngine.save_checkpoint()` also saves optimizer states? I'm asking because I do want to load the intermediate checkpoints in HF for evaluation purposes. In that case, should I call both methods? Thank you!

**Comment by hijkzzz** [comment]
you are right!

**Comment by ZhaofengWu** [comment]
Great thanks!
