### ISSUE TITLE
where is gradient_accumulation

### ISSUE THREAD

**Issue by LinglingGreat** [OpenRLHF/OpenRLHF#370]
In dpo_trainer.py, I cannot find any gradient_accumulation, I thought there should be something like if steps % gradient_accumulation == 0 before backward and optimizer_step. Did I miss anything?
<img width="675" alt="image" src="https://github.com/user-attachments/assets/77a3c91e-7fd4-4141-a907-b55c8f37e9ed">

**Comment by hijkzzz** [comment]
It is automatically managed by DeepSpeed, and the` optimizer.step` will only take effect after a number of accumulations.
