### ISSUE TITLE
现在Train_PPO_llama_ray 过程中会把Actor Model切分到不同卡上吗

### ISSUE THREAD

**Issue by shenlayu** [OpenRLHF/OpenRLHF#373]
请问现在Train_PPO_llama_ray 过程中会把Actor Model切分到不同卡上吗？如果我在使用一个很大的pertained model作为actor, 怎样能保证给其分配的几张卡的显存只占总显存的一部分？

**Comment by hijkzzz** [comment]
会的

**Comment by shenlayu** [comment]
> 会的 用 ZeRO3 即可

感谢！所以开zero2的时候，每张卡上num_gpus_per_actor无论设置为几显存都一样大是正常现象吗

**Comment by hijkzzz** [comment]
> > 会的 用 ZeRO3 即可
> 
> 感谢！所以开zero2的时候，每张卡上num_gpus_per_actor无论设置为几显存都一样大是正常现象吗？这个值是否不应该大于1？

开zero2 optimizer会切片 num_gpus_per_actor越大 占用内存越小。

**Comment by shenlayu** [comment]
感谢！不好意思还有最后一个问题。openrlhf/trainer/ray/launcher.py中的写法是
```python
for rank in range(1, world_size):
    local_rank = rank % self._num_gpus_per_node
    if pg:
        worker_actor = self.ray_actor_type.options(
            num_cpus=num_gpus_per_actor,
            num_gpus=num_gpus_per_actor,
            resources=self._resources,
            scheduling_strategy=PlacementGroupSchedulingStrategy(
                placement_group=pg,
                placement_group_bundle_index=rank // self._num_gpus_per_node,
            ),
        ).remote(world_size, rank, local_rank, master_addr, master_port)
```
也就是说创建的Actor的数量不少于Actor占用的总GPU数量？我是否可以只创建一个Actor而让其占用多个显卡，还是因为某些原因必须在每张卡上都创建一个Actor？存在更加节省显存的方式吗？十分感谢您耐心的解答！

**Comment by ChaosCodes** [comment]
> 感谢！不好意思还有最后一个问题。openrlhf/trainer/ray/launcher.py中的写法是
> 
> ```python
> for rank in range(1, world_size):
>     local_rank = rank % self._num_gpus_per_node
>     if pg:
>         worker_actor = self.ray_actor_type.options(
>             num_cpus=num_gpus_per_actor,
>             num_gpus=num_gpus_per_actor,
>             resources=self._resources,
>             scheduling_strategy=PlacementGroupSchedulingStrategy(
>                 placement_group=pg,
>                 placement_group_bundle_index=rank // self._num_gpus_per_node,
>             ),
>         ).remote(world_size, rank, local_rank, master_addr, master_port)
> ```
> 
> 也就是说创建的Actor的数量不少于Actor占用的总GPU数量？我是否可以只创建一个Actor而让其占用多个显卡，还是因为某些原因必须在每张卡上都创建一个Actor？存在更加节省显存的方式吗？十分感谢您耐心的解答！

我最近刚开始在看代码，也有类似的问题，感觉有点奇怪。这样就等于会有多个 worker 共享一个 pg
