### ISSUE TITLE
packing的问题

### ISSUE THREAD

**Issue by none0663** [OpenRLHF/OpenRLHF#377]
* sft packing 相当于把每一次 dataloader 中的micro_train_batch_size 强行组成了一条。所以我的问题是：如果micro_train_batch_size 比较大，或者每条样本都比较长的话，会导致最后packing的长度很长，是否有更优雅点的操作？还有最后packing 为啥还加了一个pad  token？
https://github.com/OpenRLHF/OpenRLHF/blob/39037369adae9d6203c104f61c0c6afdefd231fd/openrlhf/cli/train_sft.py#L71
https://github.com/OpenRLHF/OpenRLHF/blob/39037369adae9d6203c104f61c0c6afdefd231fd/openrlhf/datasets/sft_dataset.py#L139
* attention mask的问题，使用flash attention2时候，model forward 现在支持传入[1,1,1,1,2,2,2,2] 然后函数内部会自动去构建类似如下block attention了？请问transformer的版本有要求么？
<img width="693" alt="image" src="https://github.com/user-attachments/assets/8d315c66-63fb-4edd-958b-ad5a15ed91f9">

* positions ids 的问题，看model forward 时候https://github.com/OpenRLHF/OpenRLHF/blob/aae9fd4a25110a5b3770b789fff31d89c2d8c34d/openrlhf/trainer/sft_trainer.py#L122 不需要传入positions_ids, 不使用packings时候没有传入positions ids  还可以理解(应该transformers内部自己能解析，通过range(max_len)获取)，但是 packing的时候，我的理解是positions ids需要改变了，例如从[0,1,2,3,4,5,6,7,8] -->[0,1,2,3,4,0,1,2,3](假如有两笔数据,长度为5 和4 的情况下)  (rope/ALiBi等时候，应该不需要position_ids，但是其他使用绝对位置信息的，总需要position_ids吧？)
https://github.com/OpenRLHF/OpenRLHF/blob/aae9fd4a25110a5b3770b789fff31d89c2d8c34d/openrlhf/trainer/sft_trainer.py#L115

**Comment by hijkzzz** [comment]
1. pad_token 为了绕过 transformers 的检测机制，没有 0会被抛弃
2.  hf 默认不支持，需要自己hack 
3. positions_ids 对于 rope 不传也可以，直接默认 0~n

**Comment by none0663** [comment]
多谢告知。
