### ISSUE TITLE
"right" padding hardcoded

### ISSUE THREAD

**Issue by arman-z** [OpenRLHF/OpenRLHF#379]
I've noticed that "right" padding is hardcoded in several places, especially in SFT:
- https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/cli/train_sft.py#L35
- https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/datasets/sft_dataset.py#L135-L136

I was wondering if there is any particular reason for this or perhaps it is a bug? What if I want to use "left" padding as it seems to be used a lot (e.g. https://discuss.pytorch.org/t/right-vs-left-padding/185050)?

**Comment by hijkzzz** [comment]
right is recommend for sft/dpo training
left if recommend for generation

**Comment by arman-z** [comment]
But is that okay to do SFT/DPO with right padding and then use left for generation?

**Comment by hijkzzz** [comment]
> @hijkzzz But is that okay to do SFT/DPO with right padding and then use left for generation?

yes.
