### ISSUE TITLE
使用ray的时候Request Entity Too Large

### ISSUE THREAD

**Issue by hehebamei** [OpenRLHF/OpenRLHF#383]
![图片](https://github.com/user-attachments/assets/6d7eef51-cf9b-4e26-9609-8d6b21e8cf11)这里我需要怎么做才能启动程序呢

**Comment by hehebamei** [comment]
![图片](https://github.com/user-attachments/assets/ca4e336e-d679-4a5b-bfa5-2e52377a84f5)这是llama3 8b-sft-mixture

**Comment by hijkzzz** [comment]
删除项目目录下的 checkpoints 放到别的地方去

**Comment by hehebamei** [comment]
好的，之前放了的reward模型的checkpoint，马上移走。
