### ISSUE TITLE
Performance of Iterative DPO?

### ISSUE THREAD

**Issue by yesiam-png** [OpenRLHF/OpenRLHF#389]
Hi, may I know if you have evaluated the performance (e.g., Alpaca) of the resulting iterative dpo model? If not, is it available on Huggingface or somewhere?

**Comment by hijkzzz** [comment]
We evaluated the RLHF checkpoint: https://huggingface.co/OpenRLHF/Llama-3-8b-rlhf-100k
```
Chat-Arena-Hard
-------------------------------------------
llama-3-8b-sft                 | score: 5.6   
llama-3-8b-rlhf-100k           | score: 20.5
```

And, the Iterative DPO checkpoint is here: https://huggingface.co/OpenRLHF/Llama-3-8b-iter-dpo-179k
