### ISSUE TITLE
Why multiplying rstd instead of dividing by rstd?

### ISSUE THREAD

**Issue by gohsyi** [OpenRLHF/OpenRLHF#390]
https://github.com/OpenRLHF/OpenRLHF/blob/a534764229fe17a44f461712a37c84af3712a199/openrlhf/trainer/ppo_utils/replay_buffer.py#L214

When normalizing the advantages, why multiplying the standard deviation instead of dividing by the standard deviation?

**Comment by hijkzzz** [comment]
Using rstd (the reciprocal of the standard deviation's square root) instead of 1/std is primarily to avoid numerical instability.
