### ISSUE TITLE
train_ppo_ray OOM

### ISSUE THREAD

**Issue by syx11237744** [OpenRLHF/OpenRLHF#392]
我现在使用16B模型训练,请问为什么在训练的第一个step就CUDA out of memory？开zero_stage 3 并且actor_num_gpus_per_node==4，模型切到四张卡上为什么还会OOM？

具体的配置如下，虽然没有开offload,但是感觉应该不会OOM吧
  --ref_num_nodes 1 \
   --ref_num_gpus_per_node 1 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 2 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 2 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 4 \
   --vllm_num_engines 1 \
   --vllm_tensor_parallel_size 1 \
   --colocate_critic_reward \
   --ref_reward_offload \
   --pretrain /share/checkpoints/models/deepseek \
   --reward_pretrain /share/checkpoints/Meta-Llama-3-8B-Instruct \
   --save_path /openrlhf/examples/checkpoint/llama3-8b-rlhf \
   --micro_train_batch_size 4 \
   --train_batch_size 16 \
   --micro_rollout_batch_size 8 \
   --rollout_batch_size 32 \
   --max_samples 100000 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data /share/dataset/MATH/train.jsonl \
   --input_key problem \
   --normalize_reward \
   --gradient_checkpointing \

**Comment by hijkzzz** [comment]
如果需要用异构的 rm 和 actor 可以参考 https://openrlhf.readthedocs.io/en/latest/remote_rm.html
不用 adam offload 得看模型规模 大的话也很容易oom

**Comment by syx11237744** [comment]
> 如果需要用异构的 rm 和 actor 可以参考 https://openrlhf.readthedocs.io/en/latest/remote_rm.html 不用 adam offload 得看模型规模 大的话也很容易oom 而且你没开 flash_attn

我现在的pretrain的模型只有16b，如果用actor_num_gpus_per_node 4，分成4个也会oom吗？而且刚刚我测试了一下，发现开flash_attn也会oom

**Comment by hijkzzz** [comment]
可能会 理论上每张卡占用 64GB 显存，但是考虑中间激活值就会OOM（bs比较大的话）

**Comment by catqaq** [comment]
> > 如果需要用异构的 rm 和 actor 可以参考 https://openrlhf.readthedocs.io/en/latest/remote_rm.html 不用 adam offload 得看模型规模 大的话也很容易oom 而且你没开 flash_attn
> 
> 我现在的pretrain的模型只有16b，如果用actor_num_gpus_per_node 4，分成4个也会oom吗？而且刚刚我测试了一下，发现开flash_attn也会oom

先把bz开成1试试吧，4卡80G跑16B应该没啥压力的。
