### ISSUE TITLE
SFT dataset tokenization scheme bug when using llama3

### ISSUE THREAD

**Issue by ZhaofengWu** [OpenRLHF/OpenRLHF#393]
When we apply chat template + tokenize together, there is a single BOS token, as expected. But if we do them separately (as is done in https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/datasets/sft_dataset.py), two BOS tokens are added (one in each stage), which should be a bug.
```
>>> import os
>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct", token=os.environ.get("HF_TOKEN"))
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
>>> tokenizer.convert_ids_to_tokens(tokenizer.apply_chat_template([{"role": "user", "content": "test"}], add_generation_prompt=True))  # expected
['<|begin_of_text|>', '<|start_header_id|>', 'user', '<|end_header_id|>', 'ĊĊ', 'test', '<|eot_id|>', '<|start_header_id|>', 'assistant', '<|end_header_id|>', 'ĊĊ']
>>> prompt = tokenizer.apply_chat_template([{"role": "user", "content": "test"}], tokenize=False, add_generation_prompt=True)
>>> prompt
'<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\ntest<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'
>>> prompt_token = tokenizer(prompt)
>>> prompt_token
{'input_ids': [128000, 128000, 128006, 882, 128007, 271, 1985, 128009, 128006, 78191, 128007, 271], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
>>> tokenizer.convert_ids_to_tokens(prompt_token["input_ids"])
['<|begin_of_text|>', '<|begin_of_text|>', '<|start_header_id|>', 'user', '<|end_header_id|>', 'ĊĊ', 'test', '<|eot_id|>', '<|start_header_id|>', 'assistant', '<|end_header_id|>', 'ĊĊ']
```

**Comment by ZhaofengWu** [comment]
This may be an issue for other datasets too, e.g. https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/datasets/reward_dataset.py

**Comment by hijkzzz** [comment]
Interesting finding: This might be a bug in HF.

**Comment by ZhaofengWu** [comment]
That was my initial thought as well. The `tokenizer.__call__` function definitely is supposed to add BOS, so I thought maybe llama3's chat template mistakenly adds an additional BOS (https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/blob/main/tokenizer_config.json). But I just checked the chat templates for some other models (e.g. Olmo (https://huggingface.co/allenai/OLMo-7B-Instruct-hf/blob/main/tokenizer_config.json), Mistral (https://huggingface.co/mistralai/Mistral-Nemo-Instruct-2407/blob/main/tokenizer_config.json)), and they all have a BOS token in the template, so I think this is supposed to happen. I looked at the implementation of  `apply_chat_tempalte`, and it seems like they just didn't add special tokens during tokenization. So maybe we should do that too? https://github.com/huggingface/transformers/blob/026a173a64372e9602a16523b8fae9de4b0ff428/src/transformers/tokenization_utils_base.py#L1845-L1853

**Comment by ZhaofengWu** [comment]
Though, not sure if this may affect the EOS logic.

**Comment by hijkzzz** [comment]
> Though, not sure if this may affect the EOS logic.

Thanks, I will add the `add_special_tokens=False,` in tokenizer fn

**Comment by hijkzzz** [comment]
https://github.com/OpenRLHF/OpenRLHF/commit/e8bd0b76b9d44d37d349d8c8d591534576a38fcd

**Comment by ZhaofengWu** [comment]
But now, wouldn't some EOS logic be a bit weird? For example here, even when no truncation happens, we always replace the last real token with EOS.
https://github.com/OpenRLHF/OpenRLHF/blob/e8bd0b76b9d44d37d349d8c8d591534576a38fcd/openrlhf/datasets/sft_dataset.py#L117-L119

**Comment by ZhaofengWu** [comment]
Oh nvm, I think the last real token _is_ EOS when no truncation happens, so this should be a no-op in that case.

**Comment by ShengYun-Peng** [comment]
@hijkzzz @ZhaofengWu I'm curious whether explicitly replacing the EOS token is necessary. If the EOS token of a long sequence gets truncated, should we enforce an EOS in the middle of a sentence to ensure the model learns to stop at the max sequence length?
