### ISSUE TITLE
No module named 'vllm'

### ISSUE THREAD

**Issue by tbsxxxH** [OpenRLHF/OpenRLHF#400]
我运行train_ppo_llama_ray.sh时出现如下错误：
Job 'raysubmit_zrfUMAQcYUsi133j' failed

Status message: Job entrypoint command failed with exit code 1, last available logs (truncated to 20,000 chars):
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2623, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 861, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ModuleNotFoundError): ray::ActorModelRayActor.fit() (pid=59379, ip=0.0.0.0, actor_id=3a074f1fed2ae3f24c2e4c9c06000000, repr=<openrlhf.trainer.ray.ppo_actor.ActorModelRayActor object at 0x7fc97cf6e830>)
  File "/usr/local/lib/python3.10/dist-packages/openrlhf/trainer/ray/ppo_actor.py", line 336, in fit
    trainer = ActorPPOTrainer(
  File "/usr/local/lib/python3.10/dist-packages/openrlhf/trainer/ray/ppo_actor.py", line 85, in __init__
    import vllm
ModuleNotFoundError: No module named 'vllm'
但是我运行了pip install openrlhf[vllm]，并且查看pip list，也能看到vllm==0.4.2，不知道为什么运行train_ppo_llama_ray.sh时依旧提示No module named 'vllm'

**Comment by hijkzzz** [comment]
启动时加上 --runtime-env-json='{"setup_commands": ["pip install openrlhf[vllm]"]}'

**Comment by tbsxxxH** [comment]
> Ray 环境没有安装 openrlhf 启动时加上 --runtime-env-json='{"setup_commands": ["pip install openrlhf[vllm]"]}'

我之前有添加这一项，我的文件是这样的：
set -x 

ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/home/eva.liu/OpenRLHF/openrlhf"}' \
   --runtime-env-json='{"setup_commands": ["pip install openrlhf[vllm]"]}'\
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 2 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 2 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 2 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 2 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 2 \
   --colocate_critic_reward \
   --colocate_actor_ref \
   --ref_reward_offload \
   --pretrain /home/eva.liu/OpenRLHF/examples/scripts/lora_model \
   --reward_pretrain /home/eva.liu/OpenRLHF/examples/scripts/checkpoint/llama3-8b-rm \
   --save_path /openrlhf/examples/checkpoint/llama3-8b-rlhf \
   --micro_train_batch_size 8 \
   --train_batch_size 128 \
   --micro_rollout_batch_size 16 \
   --rollout_batch_size 1024 \
   --max_samples 10000 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data /home/eva.liu/OpenRLHF/datasets/datasets_rm \
   --input_key prompt \
   --normalize_reward \
   --adam_offload \
   --flash_attn \
   --gradient_checkpointing \
   --use_wandb {wandb_token}

**Comment by hijkzzz** [comment]
working_dir /home/eva.liu/OpenRLHF/ 试试?
