### ISSUE TITLE
Qlora load model error 

### ISSUE THREAD

**Issue by ldh127** [OpenRLHF/OpenRLHF#403]
get the error is this:
ngine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/maindata/data/shared/Security-SFT/common_tools/mambaforge/envs/firefly/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1112, in _configure_distributed_model
    self.module.to(self.device)
  File "/maindata/data/shared/Security-SFT/common_tools/mambaforge/envs/firefly/lib/python3.10/site-packages/accelerate/big_modeling.py", line 457, in wrapper
    return fn(*args, **kwargs)
  File "/maindata/data/shared/Security-SFT/common_tools/mambaforge/envs/firefly/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2534, in to
    raise ValueError(
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

and i use this scripts to run the openrlhf 

deepspeed examples/train_ppo.py \
  --pretrain ${sft_pretrain_model} \
  --reward_pretrain ${reward_pretrain_model} \
  --save_path ${output_dir} \
  --prompt_data ${train_data_path} \
  --input_key "prompt" \
  --input_template "<|im_start|>user\n{}<|im_end|>\n<|im_start|>assistant\n" \
  --save_steps 50 \
  --logging_steps 10 \
  --eval_steps 10 \
  --micro_train_batch_size 1 \
  --train_batch_size 256 \
  --micro_rollout_batch_size 1 \
  --rollout_batch_size 256 \
  --max_epochs 2 \
  --prompt_max_len 128 \
  --generate_max_len 256 \
  --bf16 \
  --max_norm 0.3 \
  --top_p 0.8 \
  --temperature 0.7 \
  --actor_learning_rate 5e-7 \
  --critic_learning_rate 9e-6 \
  --init_kl_coef 0.01 \
  --max_samples 10000000 \
  --normalize_reward \
  --adam_offload \
  --zero_stage 2 \
  --flash_attn \
  --gradient_checkpointing \
  --use_wandb {wandb_token} \
  --wandb_project "openrlhf_train_ppo_v1_240803" \
  --max_ckpt_num 3 \
  --lora_rank 256 \
  --lora_alpha 512 \
  --target_modules "all" \
  --disable_fast_tokenizer \
  --n_samples_per_prompt 3 \
  --load_in_4bit \
  | tee  all_exps/ppo_about/train_$RANK.log 2>&1

**Comment by hijkzzz** [comment]
see https://github.com/huggingface/transformers/issues/24540
