### ISSUE TITLE
无法用Qwen2-70b给 Qwen2-1.5b进行蒸馏 报错 tensor size 不能match

### ISSUE THREAD

**Issue by xiechengmude** [OpenRLHF/OpenRLHF#404]
`[rank1]:   File "/home/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank1]:     return forward_call(*args, **kwargs)
[rank1]:   File "/data/train/OpenRLHF/openrlhf/models/loss.py", line 251, in forward
[rank1]:     prod_probs = torch.masked_fill(teacher_probs * logprobs, inf_mask, 0)
[rank1]: RuntimeError: The size of tensor a (152064) must match the size of tensor b (151936) at non-singleton dimension 2
[rank4]: Traceback (most recent call last):
[rank4]:   File "/data/train/miniconda3/envs/openrlhf/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank4]:     return _run_code(code, main_globals, None,
[rank4]:   File "/data/train/miniconda3/envs/openrlhf/lib/python3.10/runpy.py", line 86, in _run_code
[rank4]:     exec(code, run_globals)
[rank4]:   File "/data/train/OpenRLHF/openrlhf/cli/train_kd.py", line 217, in <module>
[rank4]:     train(args)
[rank4]:   File "/data/train/OpenRLHF/openrlhf/cli/train_kd.py", line 134, in train
[rank4]:     trainer.fit(args, consumed_samples, num_update_steps_per_epoch)
[rank4]:   File "/data/train/OpenRLHF/openrlhf/trainer/kd_trainer.py", line 140, in fit
[rank4]:     distil_loss = self.kd_loss(output.logits, teacher_logits, labels)
[rank4]:   File "/home/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank4]:     return self._call_impl(*args, **kwargs)
[rank4]:   File "/home/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank4]:     return forward_call(*args, **kwargs)
[rank4]:   File "/data/train/OpenRLHF/openrlhf/models/loss.py", line 251, in forward
[rank4]:     prod_probs = torch.masked_fill(teacher_probs * logprobs, inf_mask, 0)
[rank4]: RuntimeError: The size of tensor a (152064) must match the size of tensor b (151936) at non-singleton dimension 2`

**Comment by hijkzzz** [comment]
Qwen2-1.5b 有点特殊，应该是实现有bug。
可以试试用 Qwen2 7B 蒸馏 72B。
