### ISSUE TITLE
ppo 错误

### ISSUE THREAD

**Issue by ldh127** [OpenRLHF/OpenRLHF#405]
感觉模型是开始训练了，但是 出现了这个日志之后:

next_tokens.tile(eos_token_id_tensor.shape[0], 1).ne(eos_token_id_tensor.unsqueeze(1)).prod(dim=0)

开始疯狂打了一堆数字，然后程序就崩溃了 

![image](https://github.com/user-attachments/assets/58722a84-a363-4ea3-829a-621bb15c5665)

**Comment by hijkzzz** [comment]
请使用 docker or python3.10

**Comment by ldh127** [comment]
> 请使用 docker container or python3.10

用的就是 python 3.10依然爆出来这个问题
