### ISSUE TITLE
ppo 错误

### ISSUE THREAD

**Issue by ldh127** [OpenRLHF/OpenRLHF#408]
感觉模型是开始训练了，但是
开始疯狂打了一堆数字，然后程序就崩溃了

![image](https://github.com/user-attachments/assets/b7240cc7-5462-498e-9599-b22e3f9b1c1a)

**Comment by ldh127** [comment]
@hijkzzz 使用了 python 3.10 依然爆错

**Comment by ldh127** [comment]
> @hijkzzz 使用了 python 3.10 依然爆错

程序莫名其妙的崩溃也没有提示，无语。。。

**Comment by ldh127** [comment]
> > > @hijkzzz 使用了 python 3.10 依然爆错
> > 
> > 
> > 程序莫名其妙的崩溃也没有提示，无语。。。
> 
> 上 docker

你们有打好镜像的docker吗，我这个在公司环境，不支持自己用docker里建立dock儿

**Comment by hijkzzz** [comment]
直接用 nvcr.io/nvidia/pytorch:24.02-py3

**Comment by ldh127** [comment]
> 直接用 nvcr.io/nvidia/pytorch:24.02-py3

奇怪了，我用这个镜像居然也是一样的爆错，打 一串数字数组后，程序直接崩溃了，🤔️

**Comment by ldh127** [comment]
> 直接用 nvcr.io/nvidia/pytorch:24.02-py3

为啥用这个镜像还是崩溃呢
