### ISSUE TITLE
版本冲突问题

### ISSUE THREAD

**Issue by tbsxxxH** [OpenRLHF/OpenRLHF#413]
使用了以下命令对相关包进行安装：
git clone https://github.com/OpenRLHF/OpenRLHF.git
cd OpenRLHF
pip install -e .
但是在安装完后出现了，transformer-engine和flash-attn版本不匹配的问题，我需要对flash-attn进行降级还是怎么样，降级是否会影响后续操作？另外，我用的docker环境是pytorch:24.02-py3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
transformer-engine 1.3.0+5b90b7f requires flash-attn!=2.0.9,!=2.1.0,<=2.4.2,>=2.0.6, but you have flash-attn 2.6.1 which is incompatible.

**Comment by hijkzzz** [comment]
卸载 transformer-engine ，因为用不上
