### ISSUE TITLE
AssertionError: Session name does not match persisted value

### ISSUE THREAD

**Issue by tbsxxxH** [OpenRLHF/OpenRLHF#415]
运行bash train_ppo_llama_ray.sh出现如下错误：
ConnectionError: Failed to connect to Ray at address: http://127.0.0.1:8265.
进而使用ray start --head --node-ip-address 0.0.0.0 --num-gpus 8进行启动
但是出现如下错误：
AssertionError: Session name session_2024-08-07_06-12-33_503393_3636 does not match persisted value b'session_2024-08-06_03-18-32_293071_28674'. Perhaps there was an error connecting to Redis.
目前无法使用ray，怎么解决这一情况

**Comment by hijkzzz** [comment]
https://discuss.ray.io/t/assertionerror-session-name-does-not-match-persisted-value/13067
