### ISSUE TITLE
flash_attn问题

### ISSUE THREAD

**Issue by tbsxxxH** [OpenRLHF/OpenRLHF#418]
我按照要求搭建了docker环境后执行pip uninstall xgboost transformer_engine flash_attn -y
然后执行pip install openrlhf[vllm]
运行train_ppo_llama_ray.sh时出现如下错误：
ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
于是我将flash卸载，我参考[https://github.com/OpenRLHF/OpenRLHF/issues/251](https://github.com/OpenRLHF/OpenRLHF/issues/251)
在[https://github.com/Dao-AILab/flash-attention/releases](https://github.com/Dao-AILab/flash-attention/releases/tag/v2.4.2)安装了自己cuda、torch对应版本的flash-attn。
但还是出现ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi这个问题，不知道该怎么解决....

**Comment by hijkzzz** [comment]
flash attn 2.6.1 应该没有这个问题了

**Comment by YX-S-Z** [comment]
这边试了一下, 2.6.1 依然有一样的问题:

`ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi`

**Comment by kangqiyue** [comment]
> 这边试了一下, 2.6.1 依然有一样的问题:
> 
> `ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi`

遇到同样的问题。发现是flash attention安装有问题，卸载原来的flash attention，安装和python环境的torch版本对应的flash attention

**Comment by chuangzhidan** [comment]
> > 这边试了一下, 2.6.1 依然有一样的问题:
> > `ImportError: /usr/local/lib/python3.10/dist-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi`
> 
> 遇到同样的问题。发现是flash attention安装有问题，卸载原来的flash attention，安装和python环境的torch版本对应的flash attention

我有同样的问题，怎么确定应该安装哪个版本？
