### ISSUE TITLE
请问有蒸馏的loss曲线可以参考吗

### ISSUE THREAD

**Issue by Schnabel-8** [OpenRLHF/OpenRLHF#419]
最近在用框架蒸馏模型，想参考一下默认配置下的loss曲线

**Comment by hijkzzz** [comment]
暂时没有KD 的 loss曲线可以分享呀~

**Comment by jinchenyu** [comment]
请问有结果了吗，我这边的曲线一直不如直接SFT

**Comment by Schnabel-8** [comment]
> 请问有结果了吗，我这边的曲线一直不如直接SFT

我的也是，但是评测的时候是比原模型好一点

**Comment by jinchenyu** [comment]
评测能好多少，请问您这边实验咋做的，方便详细说下吗

**Comment by jinchenyu** [comment]
感谢，请问这个teacher模型是啥，原始的llama2-70b吗，还是在数据集上SFT过的模型

**Comment by Schnabel-8** [comment]
> 感谢，请问这个teacher模型是啥，原始的llama2-70b吗，还是在数据集上SFT过的模型

是Instruct版本

**Comment by Tron1994** [comment]
发现teacher用chat模型比用base模型要好
