### ISSUE TITLE
请问这里循环处为什么设置dist.barrier()？

### ISSUE THREAD

**Issue by lyz22233** [OpenRLHF/OpenRLHF#421]
https://github.com/OpenRLHF/OpenRLHF/blob/e1205adaf163e28ed58400ed84618bc01c3c4c37/openrlhf/cli/batch_inference.py#L180

**Comment by hijkzzz** [comment]
怕最后面的那个 dist.barrier()  超时 所以每次同步一下

**Comment by lyz22233** [comment]
哦哦，学到了，感谢答疑！
