### ISSUE TITLE
How to load a open-sourced model without 'value head'

### ISSUE THREAD

**Issue by kleinzcy** [OpenRLHF/OpenRLHF#428]
Hi, I am trying to load a reward model (the final layer is reward_head) without 'value head', how to achieve that? 

In addition, I am not clear with https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/models/model.py#L187 , which will create a random initialized value head. Does it create a random initialized value head all the time?

**Comment by hijkzzz** [comment]
Please refer to the args:

https://github.com/OpenRLHF/OpenRLHF/blob/e1205adaf163e28ed58400ed84618bc01c3c4c37/openrlhf/models/model.py#L34

and 

https://github.com/OpenRLHF/OpenRLHF/blob/e1205adaf163e28ed58400ed84618bc01c3c4c37/openrlhf/models/model.py#L35

**Comment by kleinzcy** [comment]
Thanks for your reply. 

Does it mean that I can set value_head_prefix="reward_head", and setattr(self, value_head_prefix, nn.Linear(config.hidden_size, 1, bias=False))  will first search the parameters of reward_head from the model. If the parameters doesn't exist, it will initialize it with nn.Linear(config.hidden_size, 1, bias=False). 

The main misunderstanding lies in that I don't know the logic of **setattr**.
