### ISSUE TITLE
Will OpenRLHF handle gradient_accumulation_steps with loss?

### ISSUE THREAD

**Issue by mzhaoshuai** [OpenRLHF/OpenRLHF#430]
It seems that `ds_config` does not provide `gradient_accumulation_steps` for the engine initialization。

Is there any following steps handle the case where `gradient_accumulation_steps` > 1?

https://github.com/OpenRLHF/OpenRLHF/blob/46f2e69b67d5605f5032fe6160440b2a2b0f05ee/openrlhf/utils/deepspeed.py#L185-L203

https://github.com/microsoft/DeepSpeed/blob/9b7fc5452471392b0f58844219fcfdd14a9cdc77/deepspeed/runtime/engine.py#L856

**Comment by hijkzzz** [comment]
It was set by train_batch_size  / micro_train_batch_size

https://github.com/OpenRLHF/OpenRLHF/blob/46f2e69b67d5605f5032fe6160440b2a2b0f05ee/openrlhf/utils/deepspeed.py#L198

**Comment by mzhaoshuai** [comment]
> It was set by train_batch_size / micro_train_batch_size
> 
> https://github.com/OpenRLHF/OpenRLHF/blob/46f2e69b67d5605f5032fe6160440b2a2b0f05ee/openrlhf/utils/deepspeed.py#L198

Thanks for the comment.

I try to call and print `engine.gradient_accumulation_steps()` . If I do not set `ds_config["gradient_accumulation_steps"]`, there is nothing. If I set `ds_config["gradient_accumulation_steps"]`, I get a clear printing of `gradient_accumulation_steps`.

https://github.com/microsoft/DeepSpeed/blob/9b7fc5452471392b0f58844219fcfdd14a9cdc77/deepspeed/runtime/engine.py#L856-L857

I check `‎DeepSpeedEngine.set_train_batch_size()`, it will set `gradient_accumulation_steps` according to `train_micro_batch_size_per_gpu`, but I do not find where it is called.

https://github.com/microsoft/DeepSpeed/blob/9b7fc5452471392b0f58844219fcfdd14a9cdc77/deepspeed/runtime/engine.py#L455-L471

Could you please provide more information?

**Comment by hijkzzz** [comment]
See here: https://www.deepspeed.ai/docs/config-json/

**Comment by mzhaoshuai** [comment]
Thank you.
