### ISSUE TITLE
The need of micro_rollout_batch_size

### ISSUE THREAD

**Issue by Unfinito** [OpenRLHF/OpenRLHF#431]
I'm wondering whether we really need the `micro_rollout_batch_size` in PPO. Due to the rollout batch is just how many samples we need in a training in a PPO epoch, it won't affect the training batch_size or gradient_accumulation and won't cause any performance/memory issues. So use which micro_rollout to produce these samples actually doesn't matter. In the PPO code, what the `micro_rollout_batch_size` do is only to calculate the `update_timesteps`. But if we remove the `micro_rollout_batch_size`, fix the `update_timesteps = 1` and use `prompts_dataloader = strategy.setup_dataloader(prompts_dataset, args.rollout_batch_size // self.strategy.world_size, True, True)` (or remove the `rollout_batch_size` and use `micro_rollout_batch_size` to calculate it to avoid the rounding issues), the code could be simpler

**Comment by hijkzzz** [comment]
micro_rollout_batch_size  is the generation batch size per GPU
micro_train_batch_size is the training batch size per GPU

**Comment by Unfinito** [comment]
Yes, but do we really need both of the 'generation batch size per GPU'(micro_rollout_batch_size) and 'total generation batch size'(rollout_batch_size)? Isn't just use one of them and calculate the another using world_size is enough?

**Comment by Unfinito** [comment]
Oh I know your point. There may be an OOM in the generation step if the generation batch is large. I will close the issue

**Comment by pagepal666** [comment]
This modification makes no sense!!!
