### ISSUE TITLE
Is n_samples_per_prompt actually used?

### ISSUE THREAD

**Issue by Rosenberg37** [OpenRLHF/OpenRLHF#432]
checked here while find nowhere further used?
https://github.com/OpenRLHF/OpenRLHF/blob/69f52ff3d2e291a4ddef4cd667224661ba07bd94/openrlhf/cli/train_ppo_ray.py#L330

**Comment by hijkzzz** [comment]
see https://github.com/OpenRLHF/OpenRLHF/blob/69f52ff3d2e291a4ddef4cd667224661ba07bd94/openrlhf/datasets/prompts_dataset.py#L56
