### ISSUE TITLE
Support for Token-Level Rewards?

### ISSUE THREAD

**Issue by pagepal666** [OpenRLHF/OpenRLHF#433]
Has anyone tried Token-Level rewards? Are there any benefits. Why does Token-Level feel more unstable?

**Comment by hijkzzz** [comment]
Added to TODO list

**Comment by mickelliu** [comment]
What do you mean by token-level reward, do we have a reliable token-level reward model now?

Also I mean if you count KL regularization, we do have token-level reward working right now.

**Comment by pagepal666** [comment]
> What do you mean by token-level reward, do we have a reliable token-level reward model now?
> 
> Also I mean if you count KL regularization, we do have token-level reward working right now.

I feel that the reward calculation method for each token position in the current output is not suitable. Specifically, the reward at the last token position is a scalar value (including preference) after the entire sentence passes through the reward model, while the rewards at other positions are based on the KL divergence value. I understand that this reward value is only to ensure that the model does not deviate too far from the output of the reference model during the training process. Using these values to calculate the advantage function does not include the preferred reward signal; it only limits the deviation from the original output.

The corresponding value model does not contain preference information except for the last position.

I just have a gut feeling that this setup might not be the best, and I haven't done any comparative experiments to prove that token-level rewards are better than sentence-level rewards.

If, for token positions before the last one, we were to calculate the KL divergence in addition to a true reward value (for example, if we used a XXXTokenClassificationModel during the training of the reward model, which supports outputting a scalar value for each token position, would that be better? There are also other methods that support this finer-grained reward calculation (https://arxiv.org/pdf/2407.16574).)

Of course a reliable token-level reward model is more difficult to train.

**Comment by mickelliu** [comment]
Yes it's not the best approach but the current approach (implicit modeling of human preference into a single scalar) significantly reduces the efforts on data annotations collected from human lablers. Fine-grained annotations, on the other hand, are very cost-intensive. There are several papers already trying to address the problem of densifying sparse reward.

Technically speaking, token-level reward is very easy to implement once we have a good dense reward model.

**Comment by hijkzzz** [comment]
PRM status: https://github.com/OpenRLHF/OpenRLHF/pull/442

**Comment by yftah89** [comment]
Hi @hijkzzz , 
Thank you for your contributions for this repo, it's really useful!
I want to train a token-level PPO model, is it now supported by this package?
