### ISSUE TITLE
期望能支持序列并行（sequence_parallel）

### ISSUE THREAD

**Issue by kangyishuai** [OpenRLHF/OpenRLHF#435]
有长文本RLHF的需求，但是调研其他框架，目前好像没有框架能很好的支持长文本的RLHF的。期望能够支持，谢谢！！！

**Comment by hijkzzz** [comment]
Added to TODO list

**Comment by hijkzzz** [comment]
see https://github.com/OpenRLHF/OpenRLHF/pull/439

**Comment by hijkzzz** [comment]
please pip install git+https://github.com/zhuzilin/ring-flash-attention (will be changed to pip install  ring-flash-attention later)
