### ISSUE TITLE
I noticed a few calls to the get_tokenizer function in the code, but the return values were not being captured. What is the purpose of this function?

### ISSUE THREAD

**Issue by pagepal666** [OpenRLHF/OpenRLHF#440]
[train_ppo.py Line 66](https://github.com/OpenRLHF/OpenRLHF/blob/e3ffe752b15578169a1d40536c8f7e9fd9e3eeb3/openrlhf/cli/train_ppo.py#L66)

`python
get_tokenizer(args.reward_pretrain, reward_model, "left",
                      strategy, use_fast=not args.disable_fast_tokenizer)
`

line 78
`get_tokenizer(args.critic_pretrain, critic, "left", strategy,
                  use_fast=not args.disable_fast_tokenizer)`

**Comment by hijkzzz** [comment]
legacy issue~
