### ISSUE TITLE
Can't save model 

### ISSUE THREAD

**Issue by LZY-the-boys** [OpenRLHF/OpenRLHF#454]
Hi, I don't understand how to use the `working_dir` in ray ppo training. I use the following command 

````
ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "./workdir"}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \


````

When finish training , the log message gives me ```(CriticModelRayActor pid=700760, ip=xxx) [2024-10-07 10:12:38,755] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved ./ckpt/checkpoints_ppo_ray/_critic/last/bf16_zero_pp_rank_3_mp_rank_00_optim_states.pt. [repeated 7x across cluster]``` that it does save the ckpt, however I cannot find the actual ckpt in `working_dir`

**Comment by hijkzzz** [comment]
working_dir is not important
please save the final model using `--save_path /openrlhf/examples/checkpoint/llama3-8b-rlhf \`

**Comment by LZY-the-boys** [comment]
Thanks for your response, I have set the ` --save_path outs/gemma-2b-ppo \ `.  However, I cannot find the `outs` dir after training.

**Comment by hijkzzz** [comment]
It is recommended to use an absolute path.
