### ISSUE TITLE
Generation temperature for train_ppo_ray

### ISSUE THREAD

**Issue by zhenghaoxu-gatech** [OpenRLHF/OpenRLHF#469]
Hi, I found that the `temperature` argument is presented in `train_ppo.py` but not in `train_ppo_ray.py`. I manually added this argument to `train_ppo_ray.py`, but I'm unsure if it works as the `PPOTrainer` is wrapped. Will this argument be effective through `strategy`?

**Comment by hijkzzz** [comment]
See https://github.com/OpenRLHF/OpenRLHF/blob/43297e5e89324b5e095dab825798b4859a9b39b4/openrlhf/trainer/ray/ppo_actor.py#L383
