### ISSUE TITLE
关于iterative_dpo的问题

### ISSUE THREAD

**Issue by BeerTai** [OpenRLHF/OpenRLHF#479]
您好，在batch_inference.py中，rm.jsonl数据保存的格式是{"input": prompt, "output": output, "reward": reward}，然后输入到train_dpo.py中的数据也是这种格式，想咨询一下这个{"input": prompt, "output": output, "reward": reward}是如何与 chosen 和 rejected 格式的数据进行转换的？ 以及相关转换代码是在哪一部分呀？

**Comment by hijkzzz** [comment]
在这里 https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/utils/processor.py
