### ISSUE TITLE
PRM training supportting Qwen Model Series

### ISSUE THREAD

**Issue by xiechengmude** [OpenRLHF/OpenRLHF#485]
`Train epoch:   0%|          | 0/1 [00:00<?, ?it/s]              [rank0]: Traceback (most recent call last):
[rank0]:   File "/data/train/OpenRLHF/openrlhf/cli/train_prm.py", line 195, in <module>
[rank0]:     train(args)
[rank0]:   File "/data/train/OpenRLHF/openrlhf/cli/train_prm.py", line 115, in train
[rank0]:     trainer.fit(args, consumed_samples, num_update_steps_per_epoch)
[rank0]:   File "/data/train/OpenRLHF/openrlhf/trainer/prm_trainer.py", line 126, in fit
[rank0]:     for data in self.train_dataloader:
[rank0]:   File "/data/train/miniconda3/envs/openrlhf_cu2024/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/data/train/miniconda3/envs/openrlhf_cu2024/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 757, in _next_data
[rank0]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank0]:   File "/data/train/miniconda3/envs/openrlhf_cu2024/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/data/train/miniconda3/envs/openrlhf_cu2024/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/data/train/OpenRLHF/openrlhf/datasets/process_reward_dataset.py", line 67, in __getitem__
[rank0]:     assert input_token["input_ids"].numel() == label_token["input_ids"].numel()
[rank0]: AssertionError
Train epoch:   0%|          | 0/1 [00:00<?, ?it/s]
Train step of epoch 0:   0%|          | 0/55581 [00:00<?, ?it/s]`

**Comment by xiechengmude** [comment]
How to fix this raise?

**Comment by hijkzzz** [comment]
just replace + - with special tokens
