### ISSUE TITLE
Can openrlhf support using soft label during prm training process?

### ISSUE THREAD

**Issue by banksy23** [OpenRLHF/OpenRLHF#488]
Many studies have shown that soft labels are significantly more effective than hard labels.

[1] Improve Mathematical Reasoning in Language Models by Automated Process Supervision
[2] PROCESS SUPERVISION-GUIDED POLICY OPTIMIZATION FOR CODE GENERATION

**Comment by hijkzzz** [comment]
@zhuzilin

**Comment by zhuzilin** [comment]
We can do that. But we need an opensourced soft-label prm dataset to validate the implementation (and maybe implement the data format accordingly).
