### ISSUE TITLE
关于RM添加value head的疑问

### ISSUE THREAD

**Issue by Gikiman** [OpenRLHF/OpenRLHF#494]
在OpenRLHF/openrlhf/models/model.py的RewardModel类中设置了：
```python
self.value_head_prefix = value_head_prefix
setattr(self, value_head_prefix, nn.Linear(config.hidden_size, 1, bias=False))
```
请问为什么要更改输出头，并且后续也没有对RewardModel进行梯度更新

**Comment by hijkzzz** [comment]
这是RM训练的时候用的，PPO训练的时候仅读取权重。

**Comment by mickelliu** [comment]
因为有些模型的head取的名字不一样，老代码统一叫 `self.value_head` 会导致最后一层不叫这个名字的模型的最后一层weight load的不出来
