### ISSUE TITLE
请问支持对于多模态模型进行偏好训练吗？

### ISSUE THREAD

**Issue by bonre** [OpenRLHF/OpenRLHF#503]
非常感谢贵组的工作！
我在repo的使用指导当中，没有发现能够对于多模态模型的训练数据的处理。
请问目前是暂时不支持对多模态模型进行finetune吗？还是该项目是针对LLM而非MLLM呢？

**Comment by hijkzzz** [comment]
暂时不支持 多模态 目前主要开发进展都是面向都是RLHF 和 reasoning
