### ISSUE TITLE
Why loss becomes nan when training gemma-2-2b-it for reward modeling.

### ISSUE THREAD

**Issue by eyuansu62** [OpenRLHF/OpenRLHF#528]
Anyone faces same bug?

**Comment by catqaq** [comment]
can you provide your rm-layer setting? and chat_template?

**Comment by eyuansu62** [comment]
I find the reason since in the earlier version transformers, flash-attention of gemma-2 is wrong.

**Comment by eyuansu62** [comment]
@catqaq I find loss becomes nan in any version of transformers when using flash-attn. (default chat-template and layer setting)
