### ISSUE TITLE
Is this a bug? old_action_log_probs 

### ISSUE THREAD

**Issue by oleole** [OpenRLHF/OpenRLHF#529]
Maybe I missed something, but in this line
https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/trainer/ppo_trainer.py#L347
`old_action_log_probs = experience.action_log_probs`
doesn't that make action_log_probs == old_action_log_probs since both are calculated from experience?

**Comment by hijkzzz** [comment]
action_log_probs is updated in the PPO training. old_action_log_probs  is fixed.

**Comment by oleole** [comment]
That's right. Thank you!
