### ISSUE TITLE
_broadcast_to_vllm 在大规模训练中成为瓶颈

### ISSUE THREAD

**Issue by Wraythh** [OpenRLHF/OpenRLHF#533]
### 现象描述
_broadcast_to_vllm 在 worker0 节点聚合参数并 layer-by-layer 发送给所有的 vllm 引擎进行参数同步，在 vllm 引擎数量较大时，worker0 网络带宽成为瓶颈。其次，layer-by-layer 的参数同步需要频繁的切换 broadcast 算子和 load_weights 函数，使网络连接频繁的切断和连接，会增加网络传输时延。在我们的实验中粗略计算这里通信时间占比超过 40%（分一半 GPU 资源给 vllm）。
### 问题
请问后续是否会有该方面的优化或者别的考量？
### 目前想到的方案
1.利用更多的 actor 发送参数，提高传输总带宽。
2.减少 broadcast 算子和 load_weights 操作的切换次数，在 actor 上一次性发送所有的参数。

**Comment by hijkzzz** [comment]
vLLM 和 SGLang 正在协同 OpenRLHF 开发新的同步接口，敬请期待，目前基于 vLLM 0.4.2 可以稳定使用 NCCL 避免这个问题。

**Comment by hijkzzz** [comment]
> Hi @hijkzzz! 能否请问一下目前使用NCCL 从 NVLink 或者 PCI 通过 CUDA 直连具体会遇到什么问题？我使用的是6机 x 4卡A100 80G，vllm使用的是这里 #540 提及的版本，尝试给这几行注释了一下：
> 
> https://github.com/OpenRLHF/OpenRLHF/blob/83d381b77c9d53ed67272464d9acc885ceabe0b8/openrlhf/trainer/ray/ppo_actor.py#L88-L92
> 
> 确实同步速度得到了极大的提升，也没遇到任何问题。
> 
> 训练脚本：
> 
> ```shell
> ray job submit --address="http://127.0.0.1:8265" \
>    --runtime-env-json='{"working_dir": "'"$WRKDIR"'/rlhf/openrlhf_wrkdir"}' \
>    -- python3 -m openrlhf.cli.train_ppo_ray \
>    --ref_num_nodes 2 \
>    --ref_num_gpus_per_node 4 \
>    --reward_num_nodes 2 \
>    --reward_num_gpus_per_node 4 \
>    --critic_num_nodes 2 \
>    --critic_num_gpus_per_node 4 \
>    --actor_num_nodes 2 \
>    --actor_num_gpus_per_node 4 \
>    --vllm_num_engines 8 \
>    --vllm_tensor_parallel_size 1 \
>    --colocate_critic_reward \
>    --colocate_actor_ref \
>    --pretrain OpenRLHF/Llama-3-8b-sft-mixture \
>    --reward_pretrain OpenRLHF/Llama-3-8b-rm-700k \
>    --save_path ${WRKDIR}/rlhf/openrlhf_wrkdir/checkpoint/llama3-8b-rlhf \
>    --micro_train_batch_size 2 \
>    --train_batch_size 16 \
>    --micro_rollout_batch_size 4 \
>    --rollout_batch_size 64 \
>    --n_samples_per_prompt 1 \
>    --max_epochs 1 \
>    --prompt_max_len 1024 \
>    --max_samples 256 \
>    --generate_max_len 1024 \
>    --zero_stage 3 \
>    --bf16 \
>    --actor_learning_rate 5e-7 \
>    --critic_learning_rate 9e-6 \
>    --init_kl_coef 0.01 \
>    --prompt_data OpenRLHF/prompt-collection-v0.1 \
>    --input_key context_messages \
>    --apply_chat_template \
>    --normalize_reward \
>    --adam_offload \
>    --gradient_checkpointing \
>    --packing_samples \
>    --save_steps -1
> ```

请问使用的哪个版本 0.6.3 一下必须用 GLOO 不知道为什么 可以提供一下修改了什么配置和方案吗?

**Comment by HollowMan6** [comment]
> 请问是 0.6.4.post1 以后的版本可以解决吗?

是的，我这里用的是vLLM主分支里正在开发的版本

> vllm_tensor_parallel_size = 2
> NCCL 会遇到问题

我这里倒是没有遇到，即使vllm_tensor_parallel_size是2，看报错的样子是CUDA的问题，我的Driver Version是560.35.03，CUDA Version是12.6

**Comment by hijkzzz** [comment]
Fixed in https://github.com/OpenRLHF/OpenRLHF/releases/tag/v0.5.2.post1

**Comment by ZSL98** [comment]
> vLLM 和 SGLang 正在协同 OpenRLHF 开发新的同步接口，敬请期待，目前基于 vLLM 0.4.2 可以稳定使用 NCCL 避免这个问题。 Releated issue: [vllm-project/vllm#5723](https://github.com/vllm-project/vllm/issues/5723)

请问这个同步接口有release吗，求指路，非常感谢！
