### ISSUE TITLE
Any support plan for GRPO?

### ISSUE THREAD

**Issue by Rosenberg37** [OpenRLHF/OpenRLHF#535]
Both Baichuan (http://arxiv.org/abs/2410.14940) & DeepSeek (http://arxiv.org/abs/2405.04434) mention this method GPRO (https://arxiv.org/abs/2405.20304) and its potential benefits.

**Comment by hijkzzz** [comment]
see https://github.com/OpenRLHF/OpenRLHF/pull/514
we find that GRPO does not work wll.
