### ISSUE TITLE
提供的sft demo中为何不设置apply_chat_template==True

### ISSUE THREAD

**Issue by xueyongfu11** [OpenRLHF/OpenRLHF#544]
比如Repo中提供的sft demo：https://github.com/OpenRLHF/OpenRLHF/blob/main/examples/scripts/train_sft_llama.sh
并未设置apply_chat_template==True

我的理解是，sft所用的Base模型是Meta-Llama-3-8B， sft之后的模型是Meta-Llama-3-8B-Instruct，而Meta-Llama-3-8B-Instruct是有相应的chat template的。但是提供的demo中未加入apply_chat_template==True，这不是一种好的模型sft对齐的训练方式吧？谢谢

**Comment by xueyongfu11** [comment]
感谢回复。是的，base模型确实是没有apply_chat_template。

Meta-Llama-3-8B-Instruct也是从base模型Meta-Llama-3-8B中训练而来的，base模型虽然没有chat template，官方应该是在sft阶段添加了chat template。  

使用openrlhf，用base模型sft训练时还无法添加chat template，希望可以支持。

**Comment by hijkzzz** [comment]
有的: https://github.com/OpenRLHF/OpenRLHF/blob/4c87ac150514019fc28748f2f32d5226e97fddee/openrlhf/cli/train_sft.py#L197
