### ISSUE TITLE
Support GRPO?

### ISSUE THREAD

**Issue by fzyzcjy** [OpenRLHF/OpenRLHF#547]
Hi thanks for the library! It seems that GRPO is used for many mathematical and reasoning related scenarios and has good results, thus it would be great if it can be supported in this library.

**Comment by hijkzzz** [comment]
duplicate: https://github.com/OpenRLHF/OpenRLHF/issues/535

**Comment by fzyzcjy** [comment]
@hijkzzz Thank you! Btw the notion link does not seem to work (see below). 

![image](https://github.com/user-attachments/assets/78fce3be-b0fc-44e0-af8f-e2c1013f4ed9)

**Comment by hijkzzz** [comment]
https://hijkzzz.notion.site/unraveling-rlhf-and-its-variants-engineering-insights?pvs=97#147d9a33ecc9806090f3d5c749d31f05

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by fzyzcjy** [comment]
@hijkzzz Btw, do you have some ideas why GRPO seems to be adopted in math tasks? For example, is it possible that GRPO works well on and only on math
