### ISSUE TITLE
ZeroDivisionError during DPO training eval step

### ISSUE THREAD

**Issue by MarxistZ** [OpenRLHF/OpenRLHF#549]
openrlhf.cli.train_dpo \
   --save_path ./checkpoint/llama3-3b-dpo-$ds_name \
   --pretrain $pretrain \
   --dataset $dataset_dir/$ds_name \
   --save_steps -1 \
   --logging_steps 1 \
   --eval_steps -1 \
   --train_batch_size 12 \
   --micro_train_batch_size 2 \
   --bf16 \
   --max_epochs 1 \
   --max_len 4096 \
   --zero_stage 2 \
   --learning_rate 5e-7 \
   --beta 0.1 \
   --chosen_key chosen \
   --rejected_key reject \
   --flash_attn \
   --load_checkpoint \
   --gradient_checkpointing \
   --apply_chat_template \

Here is my training script, which launch with deepspeed 

The error message:

[rank5]:     self.evaluate(self.eval_dataloader, global_step)
[rank5]:   File "openrlhf/trainer/dpo_trainer.py", line 289, in evaluate
[rank5]:     "eval_loss": loss_sum / times,
[rank5]: ZeroDivisionError: division by zero

I found that if my dataset didn't contain "test" part, 
the default behavoir of 
openrlhf/utils/utils.py  -> blending_datasets
default 3% of training data will use as evaluation data.

Since my dataset is a tiny one, 3% means 34 samples, and I found that the counter variable "times" is zero.
How to fix it? can we udpate it to a safe division?

**Comment by hijkzzz** [comment]
could you help me to submit a MR to check the evaluation data loader length. It len <= 0 skip the evaluation

**Comment by MarxistZ** [comment]
> could you help me to submit a MR to check the evaluation data loader length. It len <= 0 skip the evaluation

Submit a MR, but I am not sure which branch to add the code.
