### ISSUE TITLE
问下会支持grpo么？

### ISSUE THREAD

**Issue by yiyepiaoling0715** [OpenRLHF/OpenRLHF#554]
如题，包括其他的 onlinedpo这些

**Comment by hijkzzz** [comment]
grpo 这里：https://github.com/OpenRLHF/OpenRLHF/pull/514
online dpo 就是 iterative dpo 已经支持了
不过用这两个你为什么不用我们已经支持的 REINFORCE 效果搞不好还更好

**Comment by yiyepiaoling0715** [comment]
> REINFORCE

我一直follow code/math 方向，code方向 deepseek-coder和 qwen-coder-2.5 都是基于grpo，另一个是 code/math  特别适合prm，分步骤来优化

**Comment by hijkzzz** [comment]
> > REINFORCE
> 
> 我一直follow code/math 方向，code方向 deepseek-coder和 qwen-coder-2.5 都是基于grpo，另一个是 code/math 特别适合prm，分步骤来优化

我们测过整体来说稳定性 PPO with actor_freeze (for critic init) > REINFORCE >= GRPO
不必纠结 GRPO 的那个trick, 我们也提供了RLOO 你可以对比下效果

**Comment by hwb96** [comment]
> > > REINFORCE
> > 
> > 
> > 我一直follow code/math 方向，code方向 deepseek-coder和 qwen-coder-2.5 都是基于grpo，另一个是 code/math 特别适合prm，分步骤来优化
> 
> 我们测过整体来说稳定性 PPO with actor_freeze (for critic init) > REINFORCE > GRPO 不必纠结 GRPO 的那个trick, 我们也提供了RLOO 你可以对比下效果

这里的“PPO with actor_freeze (for critic init)”,actor_freeze指的是critic模型是从actor模型来的而不是reward model来的意思吗?
