### ISSUE TITLE
使用本地数据集文件问题

### ISSUE THREAD

**Issue by lxp177** [OpenRLHF/OpenRLHF#555]
请问若想要使用DPO训练模型，使用自己本地提供的数据集文件需要在执行脚本时使用哪些参数呢？另外请问是否支持直接使用类似如下格式内容的json数据集文件：
[
    {
        "prompt": "prompt问题",
        "chosen": [
            {
                "content": "prompt问题",
                "role": "user"
            },
            {
                "content": "回答1",
                "role": "assistant"
            }
        ],
        "rejected": [
            {
                "content": "prompt问题",
                "role": "user"
            },
            {
                "content": "回答2",
                "role": "assistant"
            }
        ],
        "category": "ABC",
        "task_id": 1,
        "other_tags":"AABBCC"
    }
]

**Comment by hijkzzz** [comment]
指定 prompt chosen rejected key

**Comment by lxp177** [comment]
> 按自己的数据指定 prompt chosen rejected key 即可，参考：https://github.com/OpenRLHF/OpenRLHF/blob/main/openrlhf/datasets/reward_dataset.py#L10

非常感谢您的回复。再请问使用本地模型和本地数据集训练的话，是不是应该自己处理相关数据呢，我在使用--add_chat_template时会报错
