### ISSUE TITLE
multi-node train dpo with ring attention 

### ISSUE THREAD

**Issue by ShomyLiu** [OpenRLHF/OpenRLHF#558]
您好，感谢如此优秀的框架，关于多机训练的文档，目前发现这个：https://openrlhf.readthedocs.io/en/latest/multi-node.html 只有两个脚本，我想确认下OpenRLHF对多机DPO的支持如何了：

- 多机多卡训练70B，可能还需要Ring Attention 做序列并行+Zero3+数据并行等基本配置，不知道是否支持，
- 目前我主要参考的例子有：[train_dpo_ring_llama.sh](https://github.com/OpenRLHF/OpenRLHF/blob/main/examples/scripts/train_dpo_ring_llama.sh)  [train_ppo_llama_ray_70b.sh](https://github.com/OpenRLHF/OpenRLHF/blob/main/examples/scripts/train_ppo_llama_ray_70b.sh) 还有上面文档的两个例子

还是有些疑惑，主要是关于多机的支持、后段选择（ray，还是slurm等），再次感谢

**Comment by hijkzzz** [comment]
支持

**Comment by ShomyLiu** [comment]
感谢回复，单机的ring attention 已经用过了，赞一个。 
主要疑惑还是多机的一些设置，这方面的参考文档相对较少，所以想着先确认一下，我按照https://openrlhf.readthedocs.io/en/latest/multi-node.html#how-to-launch-sft-rm-dpo-training-on-slurm 来使用纯slurm 没有ray来配置训练ringattention+dpo多机是OK的吗

**Comment by hijkzzz** [comment]
不需要ray
