### ISSUE TITLE
Add better docs and usage examples

### ISSUE THREAD

**Issue by hijkzzz** [OpenRLHF/OpenRLHF#56]

**Comment by catqaq** [comment]
[add Verified envs and tutorial based conda](https://github.com/OpenLLMAI/OpenLLaMA2/commit/41b78829355c530c84456299ef9c3f6a72055419)

**Comment by catqaq** [comment]
[add OpenLLaMA2 Tutorial](https://github.com/OpenLLMAI/OpenLLaMA2/commit/70bef387fe2b614efca0e49b596f172a89fde86b)
