### ISSUE TITLE
Questions about configurations of 70b-ppo with ray

### ISSUE THREAD

**Issue by hashword0428** [OpenRLHF/OpenRLHF#566]
Hi! Suppose I want to train 70b-PPO with ray using the configuration in the script `examples/scripts/train_ppo_llama_ray_70b.sh`. Does it mean:
1. Suppose I'm using A100 80G (1 node with 8 gpus), **then I need 4 nodes with totally 32 gpus**?
2. **As for these gpus**:
- 8 for actor/ref (in one gpu, half actor, half ref)
- 8 for critic/reward
- 16 for vllm_engines (8 vllm_engine with each tp_size = 2)?

**Comment by hijkzzz** [comment]
yes
