### ISSUE TITLE
关于tech report中rm的数据集

### ISSUE THREAD

**Issue by LUMO666** [OpenRLHF/OpenRLHF#567]
Hello，我看到你们tech report里提到了reward model训练是用了"200k samples from the Anthropic HH, LMSys Arena , and Open Assistant  datasets"但没具体说是怎么混的，Openrlhf repo里也没找到。我想用你们的框架自己试一下rm training看看能不能复现你们tech report里从sft到ppo的整个训练流程，是否方便提供一下训练用的preference dataset呢？非常感谢！

**Comment by hijkzzz** [comment]
直接用默认数据集即可 tech report 几百年没更新了
