### ISSUE TITLE
LoRA参数设置后报错

### ISSUE THREAD

**Issue by lxp177** [OpenRLHF/OpenRLHF#569]
在尝试使用LoRA训练时发现训练开始时报错失败，我的执行脚本是：
deepspeed --module openrlhf.cli.train_dpo \
   --save_path ./checkpoint/7BInstruct_1 \
   --save_steps 1000 \
   --logging_steps 10 \
   --eval_steps -1 \
   --train_batch_size 128 \
   --micro_train_batch_size 1 \
   --pretrain /models/Qwen2.5-7B-Instruct \
   --bf16 \
   --max_epochs 1 \
   --max_len 8192 \
   --zero_stage 3 \
   --learning_rate 5e-6 \
   --beta 0.1 \
   --dataset /data/mydataset.json \
   --chosen_key chosen \
   --rejected_key rejected \
   --flash_attn \
   --load_checkpoint \
   --lora_rank 32 \
   --lora_alpha 64 \
   --lora_dropout 0.05 \
   --gradient_checkpointing
执行上述脚本后会报错：
raise CheckpointError(
[rank3]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
[rank3]: tensor at position 4:
[rank3]: saved metadata: {'shape': torch.Size([3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 6:
[rank3]: saved metadata: {'shape': torch.Size([3584, 3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 7:
[rank3]: saved metadata: {'shape': torch.Size([3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 14:
[rank3]: saved metadata: {'shape': torch.Size([512, 3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 15:
[rank3]: saved metadata: {'shape': torch.Size([512]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 22:
[rank3]: saved metadata: {'shape': torch.Size([512, 3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 23:
[rank3]: saved metadata: {'shape': torch.Size([512]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 46:
[rank3]: saved metadata: {'shape': torch.Size([3584, 3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 56:
[rank3]: saved metadata: {'shape': torch.Size([3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 58:
[rank3]: saved metadata: {'shape': torch.Size([18944, 3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 66:
[rank3]: saved metadata: {'shape': torch.Size([18944, 3584]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: tensor at position 75:
[rank3]: saved metadata: {'shape': torch.Size([3584, 18944]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
[rank3]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=3)}
不设置LoRA参数时可以正常训练，请问下是模型文件问题吗？

**Comment by hijkzzz** [comment]
干掉 --gradient_checkpointing 试试?

**Comment by lxp177** [comment]
> 干掉 --gradient_checkpointing 试试?

试了一下不用gradient_checkpointing就会报OOM错误：
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 296.00 MiB. GPU 6 has a total capacity of 79.32 GiB of which 260.44 MiB is free. Process 3427003 has 79.06 GiB memory in use. Of the allocated memory 70.31 GiB is allocated by PyTorch, and 4.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
另外也尝试改了--train_batch_size，开启--load_in_4bit都会报OOM

**Comment by hijkzzz** [comment]
https://github.com/huggingface/transformers/issues/28499

**Comment by chuangzhidan** [comment]
> > 干掉 --gradient_checkpointing 试试?
> 
> 试了一下不用gradient_checkpointing就会报OOM错误： torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 296.00 MiB. GPU 6 has a total capacity of 79.32 GiB of which 260.44 MiB is free. Process 3427003 has 79.06 GiB memory in use. Of the allocated memory 70.31 GiB is allocated by PyTorch, and 4.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) 另外也尝试改了--train_batch_size，开启--load_in_4bit都会报OOM

跟你一样，都会报OOM，奇怪，好像以前没有这种问题。请问你现在解决了吗？

**Comment by visionxyz** [comment]
一样的情况。

**Comment by lxp177** [comment]
> > > 干掉 --gradient_checkpointing 试试?
> > 
> > 
> > 试了一下不用gradient_checkpointing就会报OOM错误： torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 296.00 MiB. GPU 6 has a total capacity of 79.32 GiB of which 260.44 MiB is free. Process 3427003 has 79.06 GiB memory in use. Of the allocated memory 70.31 GiB is allocated by PyTorch, and 4.55 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) 另外也尝试改了--train_batch_size，开启--load_in_4bit都会报OOM
> 
> 跟你一样，都会报OOM，奇怪，好像以前没有这种问题。请问你现在解决了吗？

用这个格式的脚本可以试一下：
deepspeed --module openrlhf.cli.train_dpo \
   --save_path ./checkpoint/72BInstruct_12 \
   --save_steps 50 \
   --max_ckpt_num 20 \
   --logging_steps 10 \
   --use_tensorboard ./checkpoint/72BInstruct_12/log \
   --eval_steps -1 \
   --train_batch_size 128 \
   --micro_train_batch_size 1 \
   --pretrain /models/Qwen2.5-72B-Instruct \
   --bf16 \
   --max_epochs 1 \
   --max_len 4096 \
   --zero_stage 3 \
   --learning_rate 5e-7 \
   --beta 0.1 \
   --dataset /data/dataset.jsonl \
   --apply_chat_template \
   --chosen_key chosen \
   --rejected_key rejected \
   --gradient_checkpointing \
   --lora_rank 32 \
   --lora_alpha 64 \
   --lora_dropout 0.05 \
   --packing_samples \
   --adam_offload \
   --flash_attn
