### ISSUE TITLE
How to set environment variables when using ray

### ISSUE THREAD

**Issue by byerose** [OpenRLHF/OpenRLHF#571]
I need to use huggingface mirror.
export HF_ENDPOINT=https://hf-mirror.com

**Comment by hijkzzz** [comment]
export HF_ENDPOINT=https://hf-mirror.com/ before launch ray job

**Comment by byerose** [comment]
> export HF_ENDPOINT=https://hf-mirror.com/ before launch ray job

It worked.
```
--runtime-env-json='{"working_dir": "/openrlhf/OpenRLHF","env_vars": {"HF_ENDPOINT":"https://hf-mirror.com"}}'
```
