### ISSUE TITLE
Issue with packing_samples

### ISSUE THREAD

**Issue by nxphi47** [OpenRLHF/OpenRLHF#587]
Hi team,

I have concerns about the correctness of `--packing_samples`:

In OpenRLHF, if --packing on , the data will be like `attention_mask=[[1,1,1,2,2,3,3,3,0,0]]` and `position_ids=[[1,2,3,1,2,1,2,3,4,1,1]]`

In transformers [flash attention impl](https://github.com/huggingface/transformers/blob/ca03842cdcf2823301171ab27aec4b6b1cafdbc1/src/transformers/modeling_flash_attention_utils.py#L302), if `attention_mask` is passed, then `position_ids` will not be considered at all. Meanwhile, the  `attention_mask=[[1,1,1,2,2,3,3,3,0,0]]` will not be valid for this function at all, because it requires attention_mask to be only 0 or 1.

can you clarify if I'm missing something, or is there a bug?

**Comment by hijkzzz** [comment]
in hf , attention_mask will be set to None when there is no 0 in it

**Comment by nxphi47** [comment]
Got it. thanks!
