### ISSUE TITLE
Chat Template Compatibility Issue in PPO

### ISSUE THREAD

**Issue by Freder-chen** [OpenRLHF/OpenRLHF#592]
The current PPO framework causes the data to execute `apply_chat_template` within the `PromptDataset`, which forces the RM and Actor in the `experience_maker` to share the same chat template. When attempting to train the Qwen Actor using the publicly available LLaMA RM, it results in compatibility issues. I’m looking for suggestions or solutions to resolve this conflict. Could you please suggest any good solutions for this?

**Comment by hijkzzz** [comment]
please use the remote rm server

**Comment by Freder-chen** [comment]
Thank you for your suggestion! I will try using the remote rm server.

By the way, regarding your point, do you think retraining a Qwen RM would offer any training advantages compared to using the LLaMA RM?
