### ISSUE TITLE
有没有人测过 openrlhf 和 llamafactory、xtuner 比谁更快？

### ISSUE THREAD

**Issue by LinXueyuanStdio** [OpenRLHF/OpenRLHF#595]
如题。就 sft，dpo 这些

**Comment by hijkzzz** [comment]
对于 SFT DPO，更多是功能上的区别 openrlhf 代码比较简单 然后支持 ringattention

**Comment by LinXueyuanStdio** [comment]
哦哦，我看知乎好像 xtuner 以前参考过 openrlhf 的实现，个人使用下来 xtuner 比 llamafactory 快不少，就是不知道 openrlhf 有没有继续优化
