### ISSUE TITLE
Source of "Companies and Organizations using OpenRLHF"

### ISSUE THREAD

**Issue by fzyzcjy** [OpenRLHF/OpenRLHF#599]
Hi thanks for the library! It looks great, and I am curious, is there any source for the section "Companies and Organizations using OpenRLHF"? For example, how do you know Google is using it (I quickly searched but find no results)

**Comment by hijkzzz** [comment]
> Hi thanks for the library! It looks great, and I am curious, is there any source for the section "Companies and Organizations using OpenRLHF"? For example, how do you know Google is using it (I quickly searched but find no results)

from my emails or citations

**Comment by fzyzcjy** [comment]
I see. Congratulations on so many people using it!
