### ISSUE TITLE
dpo训练OOM问题

### ISSUE THREAD

**Issue by lxp177** [OpenRLHF/OpenRLHF#607]
您好，我在deepspeed dpo lora训练qwen2.5-7B-Instruct模型时正常，但训练qwen2.5-72B-Instruct时出现OOM，显存80G左右8卡，调整了batch_size、zero_stage、load_in_4bit、max_len等依旧存在问题，希望帮忙看下，谢谢！
训练脚本示例：
deepspeed --module openrlhf.cli.train_dpo \
   --save_path ./checkpoint/72BInstruct_1 \
   --save_steps 100 \
   --max_ckpt_num 20 \
   --logging_steps 10 \
   --use_tensorboard ./checkpoint/72BInstruct_1/log \
   --eval_steps -1 \
   --train_batch_size 256 \
   --micro_train_batch_size 1 \
   --pretrain /models/Qwen2.5-72B-Instruct \
   --bf16 \
   --max_epochs 1 \
   --max_len 2048 \
   --zero_stage 3 \
   --learning_rate 5e-6 \
   --beta 0.1 \
   --dataset /data/mydata364819.jsonl \
   --apply_chat_template \
   --chosen_key chosen \
   --rejected_key rejected \
   --load_in_4bit \
   --lora_rank 32 \
   --lora_alpha 64 \
   --lora_dropout 0.05 \
   --adam_offload \
   --packing_samples \
   --flash_attn 
报错问题：
[rank5]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 462.00 MiB. GPU 5 has a total capacity of 79.32 GiB of which 380.44 MiB is free. Process 732188 has 78.93 GiB memory in use. Of the allocated memory 73.18 GiB is allocated by PyTorch, and 1.61 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

开启--gradient_checkpointing，使用--zero_stage 3时则会报错如下：
[rank7]: saved metadata: {'shape': torch.Size([1024, 8192]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: tensor at position 23:
[rank7]: saved metadata: {'shape': torch.Size([1024]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: tensor at position 42:
[rank7]: saved metadata: {'shape': torch.Size([8192, 8192]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: tensor at position 52:
[rank7]: saved metadata: {'shape': torch.Size([8192]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: tensor at position 54:
[rank7]: saved metadata: {'shape': torch.Size([29568, 8192]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: tensor at position 62:
[rank7]: saved metadata: {'shape': torch.Size([29568, 8192]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: tensor at position 71:
[rank7]: saved metadata: {'shape': torch.Size([8192, 29568]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}
[rank7]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=7)}

**Comment by hijkzzz** [comment]
关闭gradient_checkpointing用ref offload ?

**Comment by lxp177** [comment]
> 关闭gradient_checkpointing用ref offload ?

感谢建议，不过尝试了一下还是会OOM。。。。。
