### ISSUE TITLE
跑ray-llama-8b的example，出现 Cuda failure 'invalid argument'，该咋解决

### ISSUE THREAD

**Issue by yyht** [OpenRLHF/OpenRLHF#616]
<img width="899" alt="企业微信截图_1f40b19d-261f-497c-bf8d-591e4e069ed6" src="https://github.com/user-attachments/assets/84196688-77d9-473f-af64-0a4e82d6d13d" />

**Comment by hijkzzz** [comment]
单机会出现这个情况 刚才1分钟前修复了 请拉取一下 或者用 gloo backend
