### ISSUE TITLE
是否有显存泄露？RM 训练显存逐步增加，最后阶段OOM退出

### ISSUE THREAD

**Issue by Anlysqx** [OpenRLHF/OpenRLHF#626]
![image](https://github.com/user-attachments/assets/db8b3f09-be8e-48e0-af72-afe22b61db50)

deepspeed --master_port 20001 --num_gpus=8 --num_nodes=1 \
   --module openrlhf.cli.train_rm \
   --save_path ./checkpoint/anlys_qwen25_7b_rm \
   --save_steps -1 \
   --logging_steps 1 \
   --eval_steps -1 \
   --train_batch_size 256 \
   --micro_train_batch_size 8 \
   --pretrain /opt/tiger/openRLHF/OpenRLHF/openrlhf_customer_models/Llama-3-8b-sft-mixture \
   --bf16 \
   --max_epochs 1 \
   --max_len 8192 \
   --zero_stage 2 \
   --learning_rate 1e-5 \
   --dataset OpenRLHF/preference_dataset_mixture2_and_safe_pku \
   --apply_chat_template \
   --chosen_key chosen \
   --rejected_key rejected \
   --flash_attn \
   --load_checkpoint \
   --gradient_checkpointing \
   --wandb_project anlys_openrlhf_train_rm_qwen \
   --wandb_run_name rm_1224_2000 
#    --use_wandb {wandb_token}

**Comment by hijkzzz** [comment]
packing_samples
