### ISSUE TITLE
experience_maker.py EOS issue

### ISSUE THREAD

**Issue by heyzude** [OpenRLHF/OpenRLHF#627]
https://github.com/OpenRLHF/OpenRLHF/blob/4c330de97be29293999e2f242232252982fca1fc/openrlhf/trainer/ppo_utils/experience_maker.py#L698C21-L698C116
For the sequence with the longest output, I guess the line should be
`output_ids = list(output.outputs[0].token_ids) + [pad_token_id] * (max_output_len - output_len + 1)` since if we don't add 1 we force the last token of the longest sequence to be changed to EOS token.

Also, I guess lines from 734 to 736 (https://github.com/OpenRLHF/OpenRLHF/blob/4c330de97be29293999e2f242232252982fca1fc/openrlhf/trainer/ppo_utils/experience_maker.py#L734)
Should be something like:
```
packed_seq_lens.append(input_len + output_len + 1)

sequences.extend(output.prompt_token_ids + list(output.outputs[0].token_ids) + [eos_token_id])

attention_mask.extend([i + 1] * (input_len + output_len + 1))
```
                    

Am I right on this issue?

**Comment by hijkzzz** [comment]
Fixed in https://github.com/OpenRLHF/OpenRLHF/commit/ce5d3cc8e902b4586851c0708f29e8606883ef36

**Comment by heyzude** [comment]
Oh, I didn't see that! thanks!
