### ISSUE TITLE
Code for the "REINFORCE++" paper

### ISSUE THREAD

**Issue by fzyzcjy** [OpenRLHF/OpenRLHF#640]
Hi thanks for the library! I am especially interested in the "mathematical scenarios", but the provided code in REINFORCE++ paper by @hijkzzz seems to be general ones (OpenRLHF/prompt-collection-v0.1). Therefore, it would be great if the scripts for the math experiments could be provided.

**Comment by hijkzzz** [comment]
https://github.com/OpenRLHF/OpenRLHF/blob/main/examples/scripts/train_reinforce_llama_ray.sh

**Comment by fzyzcjy** [comment]
@hijkzzz Thank you, but it seems https://hijkzzz.notion.site/reinforce-plus-plus says 3 experiments as follows. I would appreciate it if the experiment 2 and 3's code could be provided.

![image](https://github.com/user-attachments/assets/b99493d2-f7d8-4859-8f80-2c656ccd00e0)

**Comment by hijkzzz** [comment]
The other two experiments were not conducted by me. Here are some additional experiments: https://zhuanlan.zhihu.com/p/13872128423

**Comment by fzyzcjy** [comment]
I see, thank you!
